In [2]:
import numpy as np
np.__version__

'1.20.3'

In [4]:
import pandas as pd
pd.__version__

'1.3.2'

In [5]:
cars = pd.read_csv('data.csv')

In [6]:
cars


Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [8]:
bmw = cars[cars['Make'] == 'BMW']

In [9]:
bmw


Make       Model  Year             Engine Fuel Type  Engine HP  \
0      BMW  1 Series M  2011  premium unleaded (required)      335.0   
1      BMW    1 Series  2011  premium unleaded (required)      300.0   
2      BMW    1 Series  2011  premium unleaded (required)      300.0   
3      BMW    1 Series  2011  premium unleaded (required)      230.0   
4      BMW    1 Series  2011  premium unleaded (required)      230.0   
...    ...         ...   ...                          ...        ...   
11901  BMW          Z4  2016  premium unleaded (required)      240.0   
11902  BMW          Z4  2016  premium unleaded (required)      335.0   
11903  BMW          Z8  2001  premium unleaded (required)      394.0   
11904  BMW          Z8  2002  premium unleaded (required)      394.0   
11905  BMW          Z8  2003  premium unleaded (required)      394.0   

       Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL  rear wheel drive              2.0   
1                   6.0            MANUAL  rear wheel drive              2.0   
2                   6.0            MANUAL  rear wheel drive              2.0   
3                   6.0            MANUAL  rear wheel drive              2.0   
4                   6.0            MANUAL  rear wheel drive              2.0   
...                 ...               ...               ...              ...   
11901               4.0            MANUAL  rear wheel drive              2.0   
11902               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   
11903               8.0            MANUAL  rear wheel drive              2.0   
11904               8.0            MANUAL  rear wheel drive              2.0   
11905               8.0            MANUAL  rear wheel drive              2.0   

                             Market Category Vehicle Size Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                         Luxury,Performance      Compact   Convertible   
2                    Luxury,High-Performance      Compact         Coupe   
3                         Luxury,Performance      Compact         Coupe   
4                                     Luxury      Compact   Convertible   
...                                      ...          ...           ...   
11901                     Luxury,Performance      Compact   Convertible   
11902                Luxury,High-Performance      Compact   Convertible   
11903         Exotic,Luxury,High-Performance      Compact   Convertible   
11904         Exotic,Luxury,High-Performance      Compact   Convertible   
11905         Exotic,Luxury,High-Performance      Compact   Convertible   

       highway MPG  city mpg  Popularity    MSRP  
0               26        19        3916   46135  
1               28        19        3916   40650  
2               28        20        3916   36350  
3               28        18        3916   29450  
4               28        18        3916   34500  
...            ...       ...         ...     ...  
11901           34        22        3916   49700  
11902           24        17        3916   66350  
11903           19        12        3916  128000  
11904           19        12        3916  130000  
11905           19        12        3916  131500  

[334 rows x 16 columns]

In [12]:
bmw.describe()

Year   Engine HP  Engine Cylinders  Number of Doors  \
count   334.000000  334.000000        334.000000       334.000000   
mean   2014.347305  326.907186          5.958084         3.161677   
std       4.387983  105.681659          1.728939         0.988324   
min    1995.000000  170.000000          0.000000         2.000000   
25%    2015.000000  240.000000          4.000000         2.000000   
50%    2016.000000  300.000000          6.000000         4.000000   
75%    2016.000000  394.000000          7.500000         4.000000   
max    2017.000000  600.000000         12.000000         4.000000   

       highway MPG    city mpg  Popularity           MSRP  
count   334.000000  334.000000       334.0     334.000000  
mean     29.245509   20.739521      3916.0   61546.763473  
std      10.257037   13.136879         0.0   27982.682153  
min      18.000000   10.000000      3916.0    4697.000000  
25%      25.000000   17.000000      3916.0   42300.000000  
50%      28.000000   20.000000      3916.0   51850.000000  
75%      33.000000   22.000000      3916.0   79725.000000  
max     111.000000  137.000000      3916.0  141200.000000

In [14]:
cars[cars.Year >= 2015]

Make       Model  Year                Engine Fuel Type  Engine HP  \
32     FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
33     FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
34     FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
41      BMW    2 Series  2016     premium unleaded (required)      240.0   
42      BMW    2 Series  2016     premium unleaded (required)      240.0   
...     ...         ...   ...                             ...        ...   
11898   BMW          Z4  2015     premium unleaded (required)      300.0   
11899   BMW          Z4  2015     premium unleaded (required)      335.0   
11900   BMW          Z4  2016     premium unleaded (required)      300.0   
11901   BMW          Z4  2016     premium unleaded (required)      240.0   
11902   BMW          Z4  2016     premium unleaded (required)      335.0   

       Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
32                  4.0            MANUAL  rear wheel drive              2.0   
33                  4.0            MANUAL  rear wheel drive              2.0   
34                  4.0            MANUAL  rear wheel drive              2.0   
41                  4.0         AUTOMATIC  rear wheel drive              2.0   
42                  4.0         AUTOMATIC  rear wheel drive              2.0   
...                 ...               ...               ...              ...   
11898               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   
11899               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   
11900               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   
11901               4.0            MANUAL  rear wheel drive              2.0   
11902               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   

               Market Category Vehicle Size Vehicle Style  highway MPG  \
32                 Performance      Compact   Convertible           35   
33                 Performance      Compact   Convertible           35   
34                 Performance      Compact   Convertible           35   
41          Luxury,Performance      Compact         Coupe           35   
42                      Luxury      Compact   Convertible           34   
...                        ...          ...           ...          ...   
11898  Luxury,High-Performance      Compact   Convertible           24   
11899  Luxury,High-Performance      Compact   Convertible           24   
11900  Luxury,High-Performance      Compact   Convertible           24   
11901       Luxury,Performance      Compact   Convertible           34   
11902  Luxury,High-Performance      Compact   Convertible           24   

       city mpg  Popularity   MSRP  
32           26         819  27495  
33           26         819  24995  
34           26         819  28195  
41           23        3916  32850  
42           23        3916  38650  
...         ...         ...    ...  
11898        17        3916  56950  
11899        17        3916  65800  
11900        17        3916  57500  
11901        22        3916  49700  
11902        17        3916  66350  

[5995 rows x 16 columns]

In [20]:
engine_hp = cars[cars.Year >= 2015]['Engine HP']

In [24]:
engine_hp.isnull().sum()


51

In [27]:
engine_hp.isnull().describe()

count      5995
unique        2
top       False
freq       5944
Name: Engine HP, dtype: object

In [28]:
engine_hp.mean()


272.98771870794076

In [29]:
engine_hp.describe()

count    5944.000000
mean      272.987719
std       109.117257
min        66.000000
25%       184.000000
50%       270.000000
75%       325.000000
max       750.000000
Name: Engine HP, dtype: float64

In [30]:
engine_hp_filled = engine_hp.fillna(engine_hp.mean())

In [31]:
engine_hp_filled.describe(
)

count    5995.000000
mean      272.987719
std       108.652053
min        66.000000
25%       184.000000
50%       270.000000
75%       325.000000
max       750.000000
Name: Engine HP, dtype: float64

In [33]:
engine_hp_filled.isnull().sum()

0

In [34]:
cars


Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [38]:
rolls = cars[cars.Make == 'Rolls-Royce']

In [40]:
r2 = rolls[["Engine HP", "Engine Cylinders", "highway MPG"]]

In [41]:
r2.drop_duplicates()

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [42]:
a2 = r2.drop_duplicates().to_numpy()

In [43]:
a2

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [44]:
x = a2

In [52]:
xtx = x.T.dot(x)

In [53]:
xtx


array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [54]:
xtx_inv = np.linalg.inv(xtx)
xtx_inv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [55]:
xtx_inv.sum()

0.03221232067748617

In [56]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [57]:
w = xtx_inv.dot(x.T).dot(y)
w

array([ 0.19989598, 31.02612262, 31.65378877])